source 'http://rubygems.org'
gem 'bundler'
gem 'sinatra'
gem 'cucumber'
gem 'rspec'
gem 'capybara'
gem 'mongrel', '>= 1.2.0.pre2'
gem 'shotgun'
gem 'data_mapper'
gem 'dm-sqlite-adapter'
gem 'slim'
gem 'rack-flash'
